## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
RUN ./mvnw clean package -Dquarkus.package.type=mutable-jar
#RUN ./mvnw install -Dquarkus.package.type=mutable-jar -Dquarkus.live-reload.password=changeit -Dquarkus.live-reload.url=http://0.0.0.0:8080
ENTRYPOINT [ "java", "-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005", "-Dquarkus.live-reload.password=123", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=8080", "/code/target/quarkus-app/quarkus-run.jar"]