#/*******************************************************************************
#* Licensed Materials - Property of HCL
#* (c) Copyright HCL Technologies Ltd. 2023. All Rights Reserved.
#
#* Note to U.S. Government Users Restricted Rights:
#* Use, duplication or disclosure restricted by GSA ADP Schedule
#**************************************************************/
version: "3.0"

services:
    hello-world:
        build:
            context: .
            dockerfile: "Dockerfile.debug"
            target: remote-debug
        container_name: hello-world
        labels:
        - "version=0.0.1"
        environment:
            - "DISABLE_INSTALL_DEMO_CONFIG=true"
            - "QUARKUS_LAUNCH_DEVMODE=true"
        networks:
            - eth-events-reader-net
        ports:
            - 8080:8080
    #       - 5005:5005
        volumes:
            - eth-events-reader-data:/usr/share/opensearch/data
        restart: unless-stopped

# Local volumes cannot be used for deployment in clusters
volumes:
    eth-events-reader-data:

networks:
    eth-events-reader-net:
